# Generated by Django 2.1.5 on 2019-02-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(default='Miami', max_length=60)),
                ('state', models.CharField(default='Florida', max_length=30)),
                ('zipcode', models.CharField(default='3365', max_length=5)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
