# Generated by Django 2.1.5 on 2019-02-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_homeaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAddress',
        ),
    ]
