# Generated by Django 2.1.5 on 2019-02-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190210_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
            preserve_default=False,
        ),
    ]
