# Generated by Django 2.1.5 on 2019-02-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190226_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Nick name'),
        ),
    ]
