# Generated by Django 2.1.5 on 2019-02-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
