# Generated by Django 2.1.5 on 2019-03-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190301_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='FL', max_length=128, verbose_name='State'),
        ),
    ]
