# Generated by Django 2.1.5 on 2019-03-02 19:20

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190301_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(default='FL', max_length=2, verbose_name='State'),
        ),
    ]
