# Generated by Django 2.1.5 on 2019-03-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190302_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('name',), 'verbose_name_plural': 'Address'},
        ),
    ]
