# Generated by Django 2.1.5 on 2019-03-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190302_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
