# Generated by Django 2.1.5 on 2019-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190302_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primaryAddress',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
