# Generated by Django 2.1.5 on 2019-03-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_creditcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'Credit Card', 'verbose_name_plural': 'Credit Cards'},
        ),
    ]
