# Generated by Django 2.1.5 on 2019-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190323_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
