# Generated by Django 2.1.5 on 2019-03-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_creditcard_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='slug',
        ),
    ]
