# Generated by Django 2.1.5 on 2019-02-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ('author_name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(db_index=True, max_length=80)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('book_author', models.CharField(max_length=200)),
                ('author_bio', models.CharField(max_length=1000)),
                ('book_description', models.CharField(max_length=1000)),
                ('book_genre', models.CharField(max_length=100)),
                ('publishing_info', models.CharField(max_length=200)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'ordering': ('book_name',),
            },
        ),
    ]
