# Generated by Django 2.1.5 on 2019-04-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0005_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='User',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='book',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
