# Generated by Django 2.1.5 on 2019-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0008_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(max_length=150),
        ),
    ]
