# Generated by Django 2.1.5 on 2019-04-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_creditcard_slug'),
        ('bookDetails', '0010_auto_20190412_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_purchased', models.BooleanField(blank=True, default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookDetails.Book')),
            ],
        ),
    ]
