# Generated by Django 2.1.5 on 2019-05-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_creditcard_slug'),
        ('bookDetails', '0014_auto_20190512_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
