# Generated by Django 2.1.5 on 2019-05-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0015_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
