# Generated by Django 2.1.5 on 2019-05-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0017_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='has_purchased',
        ),
    ]
