# Generated by Django 2.1.5 on 2019-02-10 20:44
# Generated by Django 2.1.5 on 2019-02-16 03:17


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_description', models.CharField(max_length=1000)),
                ('book_genre', models.CharField(max_length=20)),
                ('book_info', models.CharField(max_length=100)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
