# Generated by Django 2.1.5 on 2019-02-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_num',
            field=models.IntegerField(verbose_name=(1, 2)),
        ),
    ]
