# Generated by Django 2.1.5 on 2019-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookDetails', '0001_initial'),
        ('wishlist', '0002_auto_20190228_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='list_name',
        ),
        migrations.RemoveField(
            model_name='list',
            name='list_num',
        ),
        migrations.AddField(
            model_name='list',
            name='books',
            field=models.ManyToManyField(to='bookDetails.Book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
