# Generated by Django 2.1.5 on 2019-02-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20190228_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='books',
            field=models.ManyToManyField(blank=True, to='bookDetails.Book'),
        ),
    ]
