# Generated by Django 2.1.5 on 2019-03-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20190303_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('user', 'date_created')},
        ),
    ]
