# Generated by Django 2.1.5 on 2019-04-11 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_auto_20190411_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
